services:
  - type: web
    name: disease-prediction-app
    env: python
    buildCommand: "pip install -r required_files/requirements.txt && python required_files/manage.py collectstatic --noinput"
    startCommand: "gunicorn minor.wsgi:application --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: minor.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DISABLE_COLLECTSTATIC
        value: 0
    autoDeploy: true
    plan: free
    numInstances: 1
    healthCheckPath: /
